---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allow-argocd-to-manage.yaml
  - openshift-operator.yaml
  - tekton-config.yaml
  - clusterrole.yaml
  - pipelines-scc-v2.yaml
